# Generated by Django 4.1.7 on 2023-04-07 19:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "price_per_night",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "max_guests",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[("available", "available"), ("reserved", "reserved")],
                        default="available",
                        max_length=12,
                    ),
                ),
                ("bathrooms", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("backyard", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                ("wifi", models.BooleanField(default=False)),
                ("kitchen", models.BooleanField(default=False)),
                ("free_parking", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                (
                    "banned",
                    models.ManyToManyField(
                        related_name="banned_properties", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "current_renter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rented_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "images",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="images.image",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
