# Generated by Django 4.1.5 on 2023-03-03 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.IntegerField(choices=[(0, 'Unseen'), (1, 'Seen')], default=0)),
                ('link', models.URLField(default='http://restify.com/notifications/test')),
                ('notification_type', models.CharField(choices=[('new_reservation', 'New Reservation'), ('cancellation_request', 'Cancellation Request'), ('approved_reservation', 'Approved Reservation'), ('cancellation_approved', 'Cancellation Approved')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
