# Generated by Django 4.1.5 on 2023-03-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(default='http://google.com/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_reservation', 'New Reservation'), ('cancellation_request', 'Cancellation Request'), ('approved_reservation', 'Approved Reservation'), ('cancellation_approved', 'Cancellation Approved'), ('test_notification', 'Test notification from Phase 2 of Restify!')], default='test_notification', max_length=50),
        ),
    ]
