# Generated by Django 4.1.7 on 2023-04-07 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reservation_request", "You have a Reservation Request"),
                            ("cancellation_request", "You have a Cancellation Request"),
                            (
                                "reservation_approved",
                                "Your Reservation Request was Approved",
                            ),
                            (
                                "cancellation_approved",
                                "Your Cancellation Request Approved",
                            ),
                            (
                                "property_comment",
                                "Someone left a comment on your property!",
                            ),
                            (
                                "test_notification",
                                "Test notification from Phase 2 of Restify!",
                            ),
                        ],
                        default="test_notification",
                        max_length=50,
                    ),
                ),
                (
                    "seen",
                    models.IntegerField(
                        choices=[(0, "Unseen"), (1, "Seen")], default=0
                    ),
                ),
                ("link", models.URLField(default="http://google.com/")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
